# install_ipa_server.yml
# Chen Chang <cchang@redhat.com>

- hosts: 192.168.1.198
  become: true

  vars:

    ipa_domain: lab.example.com
    ipa_realm: LAB.EXAMPLE.COM
    ipa_ds_password: Redhat123       # This is the directory manager password
    ipa_admin_password: Redhat123    # This is the initial password for the 'admin' IPA superuser (web UI)
    ipa_server_packages:
      - ipa-server
      - ipa-server-dns
    ipa_firewalld_services:
      - freeipa-ldap
      - freeipa-ldaps
      - dns
    ntp_server: id.pool.ntp.org

  tasks:
    - name: Create ipa_pwd_extop plugin modification ldif
      copy:
        dest: /root/ipa_pwd_extop.ldif
        content: |
          dn: cn=ipa_pwd_extop,cn=plugins,cn=config
          changetype: modify
          add: passSyncManagersDNs
          passSyncManagersDNs: uid=admin,cn=users,cn=accounts,dc=lab,dc=example,dc=com

    - name: Add passSyncManagersDNs attribute to ipa_pwd_extop plugin
      shell: |
        ldapmodify -x -D "cn=Directory Manager" \
        -w {{ ipa_ds_password }} \
        -h idm.lab.example.com \
        -p 389 \
        -f /root/ipa_pwd_extop.ldif
      args:
        executable: /usr/bin/bash
      register: ldapmodify_result
      failed_when: ldapmodify_result.rc != 0 and ldapmodify_result.rc != 20
   
    
